// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKbDYGlddJAiuT1Redqt4HxFHHiMyiANE',
    appId: '1:261978551922:web:10ba7f814902cd4e9d34eb',
    messagingSenderId: '261978551922',
    projectId: 'notes-app-with-multiple-users',
    authDomain: 'notes-app-with-multiple-users.firebaseapp.com',
    storageBucket: 'notes-app-with-multiple-users.firebasestorage.app',
    measurementId: 'G-LTMYJCJSK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl3Ok3KdrIXvkS2NsoWBBZKFzemi_IyYs',
    appId: '1:261978551922:android:c6dc60184a5827b99d34eb',
    messagingSenderId: '261978551922',
    projectId: 'notes-app-with-multiple-users',
    storageBucket: 'notes-app-with-multiple-users.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4omC0vUwek5WcSrsz-wfDAlDBKpGMx6k',
    appId: '1:261978551922:ios:dc8f71cf97a9c76d9d34eb',
    messagingSenderId: '261978551922',
    projectId: 'notes-app-with-multiple-users',
    storageBucket: 'notes-app-with-multiple-users.firebasestorage.app',
    iosBundleId: 'com.example.notesAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4omC0vUwek5WcSrsz-wfDAlDBKpGMx6k',
    appId: '1:261978551922:ios:dc8f71cf97a9c76d9d34eb',
    messagingSenderId: '261978551922',
    projectId: 'notes-app-with-multiple-users',
    storageBucket: 'notes-app-with-multiple-users.firebasestorage.app',
    iosBundleId: 'com.example.notesAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKbDYGlddJAiuT1Redqt4HxFHHiMyiANE',
    appId: '1:261978551922:web:7ed8dac4c7320f9a9d34eb',
    messagingSenderId: '261978551922',
    projectId: 'notes-app-with-multiple-users',
    authDomain: 'notes-app-with-multiple-users.firebaseapp.com',
    storageBucket: 'notes-app-with-multiple-users.firebasestorage.app',
    measurementId: 'G-9Q8S01CZDN',
  );
}
